# Generated by Django 5.1.2 on 2024-11-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to='uploads/catalog/% Y/% m/% d/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
