# Generated by Django 5.1.2 on 2024-11-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Основной товар'),
            preserve_default=False,
        ),
    ]
