# Generated by Django 5.1.2 on 2024-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_producttype_price_producttype_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='photo',
            field=models.ImageField(default='', upload_to='uploads/catalog/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
