# Generated by Django 5.1.2 on 2024-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producttype_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='left',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='photo',
            field=models.ImageField(upload_to='uploads/catalog/', verbose_name=' Фотография'),
        ),
    ]
