# Generated by Django 5.1.2 on 2025-01-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_price'),
        ('main', '0003_alter_shops_shop_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='left',
        ),
        migrations.CreateModel(
            name='ProductTypeShopLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(default=0, verbose_name='Остаток')),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.producttype', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shops', verbose_name='Магазин')),
            ],
        ),
    ]
