# Generated by Django 5.1.2 on 2025-01-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_producttype_left_producttypeshopleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='external_code',
            field=models.CharField(default='', max_length=127, verbose_name='Внешний код'),
        ),
        migrations.AddField(
            model_name='material',
            name='external_code',
            field=models.CharField(default='', max_length=127, verbose_name='Внешний код'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_code',
            field=models.CharField(default='', max_length=127, verbose_name='Внешний код'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='external_code',
            field=models.CharField(default='', max_length=127, verbose_name='Внешний код'),
        ),
        migrations.AddField(
            model_name='size',
            name='external_code',
            field=models.CharField(default='', max_length=127, verbose_name='Внешний код'),
        ),
    ]
