# Generated by Django 5.1.2 on 2025-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_color_external_code_material_external_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='sizeit',
            field=models.CharField(default='', max_length=127, verbose_name='Размер '),
        ),
        migrations.AddField(
            model_name='size',
            name='sizeru',
            field=models.CharField(default='', max_length=127, verbose_name='Размер ru'),
        ),
    ]
