# Generated by Django 5.1.2 on 2025-01-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_size_sizeit_size_sizeru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizeit',
            field=models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Размер '),
        ),
        migrations.AlterField(
            model_name='size',
            name='sizeru',
            field=models.CharField(blank=True, default='', max_length=127, null=True, verbose_name='Размер ru'),
        ),
    ]
