# Generated by Django 5.1.2 on 2025-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_size_sizeit_alter_size_sizeru'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='external_code',
            field=models.CharField(default='', max_length=127, verbose_name='Внешний код'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/catalog/', verbose_name='Фотография'),
        ),
    ]
