# Generated by Django 5.1.2 on 2025-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_collections_external_code_alter_collections_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('external_code', models.CharField(default='', max_length=127, verbose_name='Внешний код')),
            ],
        ),
    ]
