# Generated by Django 5.1.2 on 2025-01-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_image',
            field=models.BooleanField(blank=True, null=True, verbose_name='Большая картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/catalog/', verbose_name='Фотография'),
        ),
    ]
