# Generated by Django 5.1.2 on 2025-01-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_big_image_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypeshopleft',
            name='external_code',
            field=models.CharField(default='', max_length=127, verbose_name='Внешний код'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/catalog/', verbose_name=' Фотография'),
        ),
    ]
