# Generated by Django 5.1.2 on 2024-12-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=127, verbose_name='Телефон')),
                ('photo', models.ImageField(upload_to='uploads/shop/', verbose_name='Фотография')),
                ('shop_type', models.CharField(choices=[('Торговые центры', 'Tc'), ('Аутлеты', 'Autlet'), ('Корнеры', 'Corner')], max_length=127, verbose_name='Тип заказа')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(default='', max_length=127, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
