# Generated by Django 5.1.2 on 2024-12-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shops_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='shop_type',
            field=models.CharField(choices=[('Торговые центры', 'Tc'), ('Аутлеты', 'Autlet'), ('Корнеры', 'Corner')], max_length=127, verbose_name='Тип магазина'),
        ),
    ]
