# Generated by Django 5.1.2 on 2025-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shops_external_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='phone',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('Торговые центры', 'Tc'), ('Аутлеты', 'Autlet'), ('Корнеры', 'Corner')], max_length=127, null=True, verbose_name='Тип магазина'),
        ),
    ]
