CREATE TABLE IF NOT EXISTS "catalog_color" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL, "color_code" varchar(63) NOT NULL);
CREATE TABLE IF NOT EXISTS "catalog_material" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL);
CREATE TABLE IF NOT EXISTS "catalog_size" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL);
CREATE TABLE IF NOT EXISTS "catalog_producttypephotos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "photo" varchar(100) NOT NULL, "producttype_id" bigint NOT NULL REFERENCES "catalog_producttype" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "catalog_producttypephotos_producttype_id_5f2cec95" ON "catalog_producttypephotos" ("producttype_id");
CREATE TABLE IF NOT EXISTS "main_newsphotos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "photo" varchar(100) NOT NULL, "news_id" bigint NOT NULL REFERENCES "main_news" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "main_newsphotos_news_id_4f764db4" ON "main_newsphotos" ("news_id");
CREATE TABLE IF NOT EXISTS "personal_customer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "birth_date" date NULL, "phone_number" varchar(63) NULL, "photo" varchar(100) NULL, "cart" text NULL CHECK ((JSON_VALID("cart") OR "cart" IS NULL)), "favourites" text NULL CHECK ((JSON_VALID("favourites") OR "favourites" IS NULL)), "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "catalog_producttype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL, "color_id" bigint NULL REFERENCES "catalog_color" ("id") DEFERRABLE INITIALLY DEFERRED, "material_id" bigint NULL REFERENCES "catalog_material" ("id") DEFERRABLE INITIALLY DEFERRED, "size_id" bigint NULL REFERENCES "catalog_size" ("id") DEFERRABLE INITIALLY DEFERRED, "price" integer NOT NULL, "product_id" bigint NOT NULL REFERENCES "catalog_product" ("id") DEFERRABLE INITIALLY DEFERRED, "photo" varchar(100) NOT NULL, "left" integer NOT NULL);
CREATE INDEX "catalog_producttype_color_id_4aecab3f" ON "catalog_producttype" ("color_id");
CREATE INDEX "catalog_producttype_material_id_da881e5c" ON "catalog_producttype" ("material_id");
CREATE INDEX "catalog_producttype_size_id_43798979" ON "catalog_producttype" ("size_id");
CREATE INDEX "catalog_producttype_product_id_101b3f13" ON "catalog_producttype" ("product_id");
CREATE TABLE IF NOT EXISTS "catalog_collections" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL, "photo" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "catalog_product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL, "description" text NULL, "show_on_main_page" bool NOT NULL, "big_image" bool NOT NULL, "photo" varchar(100) NOT NULL, "collection_id" bigint NULL REFERENCES "catalog_collections" ("id") DEFERRABLE INITIALLY DEFERRED, "price" integer NOT NULL);
CREATE INDEX "catalog_product_collection_id_ddea8d85" ON "catalog_product" ("collection_id");
CREATE TABLE IF NOT EXISTS "main_shops" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL, "address" varchar(255) NOT NULL, "phone" varchar(127) NOT NULL, "photo" varchar(100) NOT NULL, "shop_type" varchar(127) NOT NULL);
CREATE TABLE IF NOT EXISTS "main_news" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(127) NOT NULL, "date" date NOT NULL, "photo" varchar(100) NOT NULL, "first_description" text NULL, "second_description" text NULL, "slug" varchar(127) NOT NULL);
CREATE TABLE IF NOT EXISTS "order_order_cart_items" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "order_id" bigint NOT NULL REFERENCES "order_order" ("id") DEFERRABLE INITIALLY DEFERRED, "producttype_id" bigint NOT NULL REFERENCES "catalog_producttype" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "order_order_cart_items_order_id_producttype_id_ca7013a9_uniq" ON "order_order_cart_items" ("order_id", "producttype_id");
CREATE INDEX "order_order_cart_items_order_id_365108c6" ON "order_order_cart_items" ("order_id");
CREATE INDEX "order_order_cart_items_producttype_id_f453291b" ON "order_order_cart_items" ("producttype_id");
CREATE TABLE IF NOT EXISTS "order_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NULL, "order_type" varchar(127) NOT NULL, "customer_id" bigint NULL REFERENCES "personal_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "last_name" varchar(127) NULL, "mail" varchar(127) NULL, "name" varchar(127) NULL, "phone_number" varchar(63) NULL, "shop_id" bigint NOT NULL REFERENCES "main_shops" ("id") DEFERRABLE INITIALLY DEFERRED, "price" integer NOT NULL, "order_status" varchar(127) NOT NULL);
CREATE INDEX "order_order_customer_id_5bbbd957" ON "order_order" ("customer_id");
CREATE INDEX "order_order_shop_id_ede10ed8" ON "order_order" ("shop_id");
