# Generated by Django 5.1.2 on 2024-12-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shops_shop_type'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='mail',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.shops', verbose_name='Магазин'),
            preserve_default=False,
        ),
    ]
