# Generated by Django 5.1.2 on 2024-12-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_price'),
        ('order', '0002_order_last_name_order_mail_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='catalog.producttype'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
