# Generated by Django 5.1.2 on 2024-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_customer_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('В обработке', 'Waiting'), ('Оплачен', 'Payed')], default='В обработке', max_length=127, verbose_name='Статус заказа'),
        ),
    ]
